config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/auth/do_omniauth', to: 'omniauth_callbacks#do_omniauth', as: :auth_callback_do
    get '/users/auth/service_sign_up', to: 'omniauth_callbacks#service_sign_up_users', as: :service_sign_up_users
    post '/users/auth/create_user_and_service', to: 'omniauth_callbacks#create_user_and_service', as: :create_user_and_service
  end

#  authenticated(:user) do

    resource :user_profile, only: [:show, :update], controller: 'user_profile/users', as: :user_profile
    scope module: :user_profile do
      resources :services, only: [:destroy], as: :user_profile_services
    end

    resource :user_cabinet, only: [:show, :update], controller: 'user_cabinet/users', as: :user_cabinet
    namespace :user_cabinet do
      resources :galleries
      resource :category, only: :update
      resources :articles
    end


    # patch 'users/:id/update_category', to: 'user_cabinet/users#update_category', as: :user_update_category
    #
    # resources :users, only: [:show, :edit, :update] do
    #   get :profile, on: :member, to: 'user_profile/users#show', as: :user_profile
    #   put :profile, on: :member, to: 'user_profile/users#update'
    #
    #   scope module: 'user_profile' do
    #     resources :services, only: [:destroy]
    #   end
    #
    #   get :cabinet, on: :member, to: 'user_cabinet/users#show', as: :user_cabinet
    #   scope module: 'user_cabinet' do
    #     resources :galleries
    #     resources :pictures
    #   end
    #
    #   resources :articles
    # end
    #
    # resources :grades
    # resources :articles, only: [:index, :show]
#    root to: "secret#index", as: :authenticated_root
#  end

  resources :grades, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :galleries, only: [:index, :show]
  root to: 'home#index'

  def authenticated_root
    user_profile
  end
end

app/views/admin/_picture_gallery_show.html.haml
.section
  = link_to 'New picture', new_admin_picture_path(the_picture: { gallery_id: gallery.id }, back: defined?(back) ? back : nil ), class: 'button'
.section
  - gallery.pictures.each do |picture|
    = render 'admin/picture_preview', picture: picture

app/views/admin/_picture_preview.html.haml
.admin_image_full_preview
  .image
    = attached_image_tag(picture, { width: 100, height: 100 })
  .image_title
    = picture.name
  .image_descrption
    = picture.description
  .image_tools.action_items
    %span.action_item
      = link_to('View',  admin_picture_path(id: picture.id, back: request.url))
      = link_to('Edit',  edit_admin_picture_path(id: picture.id, back: request.url), class: 'action_item')

app/views/admin/_services_table.html.haml
.section
  %table
    %thead
      %tr
        %th
          = Service.human_attribute_name(:provider)
        %th
          = Service.human_attribute_name(:uid)
        %th
          = Service.human_attribute_name(:uname)
        %th
          = Service.human_attribute_name(:uemail)

    %tbody
      - services.each do |service|
        %tr
          %td
            = link_to service.provider, admin_service_path(service)
          %td
            = service.uid
          %td
            = service.uname
          %td
            = service.uemail