config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/auth/do_omniauth', to: 'omniauth_callbacks#do_omniauth', as: :auth_callback_do
    get '/users/auth/service_sign_up', to: 'omniauth_callbacks#service_sign_up_users', as: :service_sign_up_users
    post '/users/auth/create_user_and_service', to: 'omniauth_callbacks#create_user_and_service', as: :create_user_and_service
  end

#  authenticated(:user) do

    resource :user_profile, only: [:show, :update], controller: 'user_profile/users', as: :user_profile
    scope module: :user_profile do
      resources :services, only: [:destroy], as: :user_profile_services
    end

    resource :user_cabinet, only: [:show, :update], controller: 'user_cabinet/users', as: :user_cabinet
    namespace :user_cabinet do
      resources :galleries
      resource :category, only: :update
      resources :articles
    end


    # patch 'users/:id/update_category', to: 'user_cabinet/users#update_category', as: :user_update_category
    #
    # resources :users, only: [:show, :edit, :update] do
    #   get :profile, on: :member, to: 'user_profile/users#show', as: :user_profile
    #   put :profile, on: :member, to: 'user_profile/users#update'
    #
    #   scope module: 'user_profile' do
    #     resources :services, only: [:destroy]
    #   end
    #
    #   get :cabinet, on: :member, to: 'user_cabinet/users#show', as: :user_cabinet
    #   scope module: 'user_cabinet' do
    #     resources :galleries
    #     resources :pictures
    #   end
    #
    #   resources :articles
    # end
    #
    # resources :grades
    # resources :articles, only: [:index, :show]
#    root to: "secret#index", as: :authenticated_root
#  end

  resources :grades, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :galleries, only: [:index, :show]
  root to: 'home#index'

  def authenticated_root
    user_profile
  end
end

app/views/layouts/template_parts/_bottom.html.erb
<section id="bottom">
  <div class="container fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
    <div class="row">
      <div class="col-md-2">
        <a href="#" class="footer-logo">
          <%= image_tag 'images/logo-black.png', alt: 'logo' %>
        </a>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Company</h3>
              <ul>
                <li><a href="#">About us</a></li>
                <li><a href="#">We are hiring</a></li>
                <li><a href="#">Meet the team</a></li>
                <li><a href="#">Copyright</a></li>
                <li><a href="#">Terms of use</a></li>
                <li><a href="#">Privacy policy</a></li>
                <li><a href="#">Contact us</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->

          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Support</h3>
              <ul>
                <li><a href="#">Faq</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Forum</a></li>
                <li><a href="#">Documentation</a></li>
                <li><a href="#">Refund policy</a></li>
                <li><a href="#">Ticket system</a></li>
                <li><a href="#">Billing system</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->

          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Developers</h3>
              <ul>
                <li><a href="#">Web Development</a></li>
                <li><a href="#">SEO Marketing</a></li>
                <li><a href="#">Theme</a></li>
                <li><a href="#">Development</a></li>
                <li><a href="#">Email Marketing</a></li>
                <li><a href="#">Plugin Development</a></li>
                <li><a href="#">Article Writing</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->

          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Our Partners</h3>
              <ul>
                <li><a href="#">Adipisicing Elit</a></li>
                <li><a href="#">Eiusmod</a></li>
                <li><a href="#">Tempor</a></li>
                <li><a href="#">Veniam</a></li>
                <li><a href="#">Exercitation</a></li>
                <li><a href="#">Ullamco</a></li>
                <li><a href="#">Laboris</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->
        </div>
      </div>


    </div>
  </div>
</section>

app/views/layouts/template_parts/_copyright.html.erb
<div id="copyright">
  <div class="container">
    <div class="row">
      <div class="left span6">
        <p>
          <a href="http://yithemes.com/"><img src="http://yithemes.com/cdn/images/various/footer_yith_grey.png" alt="Your Inspiration Themes" style="position:relative; top:9px; margin: -22px 5px 0 0;"></a>&nbsp;Copyright 2012 - <strong>Libra theme</strong> by
          Your Inspiration Themes
        </p>
      </div>
      <div class="right span6">
        <p>
          <a href="http://yithemes.com/themes/wordpress/libra-corporate-portfolio-wp-theme/?ap_id=libra-html"><strong>Download the free version for Wordpress</strong></a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/template_parts/_footer.html.erb
<footer id="footer" class="midnight-blue">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
      </div>
      <div class="col-sm-6">
        <ul class="pull-right">
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Faq</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/template_parts/_large_title.html.haml
.large-title.text-center
  %h2
    = locals[:title]
  %p
    = simple_format(locals[:text])

app/views/layouts/template_parts/_main_navigation.html.erb
<ul id="menu-menu" class="level-1">
  <li>
    <a href="index.html">HOME</a>
    <ul class="sub-menu">
      <li><a href="home-ii.html">Home II</a></li>
      <li><a href="home-iii.html">Home III</a></li>
      <li><a href="home-iv.html">Home IV</a></li>
      <li><a href="home-v.html">Home V</a></li>
      <li><a href="home-vi.html">Home VI</a></li>
      <li><a href="home-vii.html">Home VII</a></li>
      <li class="current_page_item"><a href="home-viii.html">Home VIII</a></li>
      <li><a href="home-ix.html">Home IX</a></li>
      <li><a href="home-x.html">Home X</a></li>
    </ul>
  </li>
  <li>
    <a href="#">SLIDERS</a>
    <ul class="sub-menu">
      <li><a href="revolution-slider.html">Revolution Slider</a></li>
      <li><a href="flexslider-classic.html">Flexslider Classic</a></li>
      <li><a href="flexslider-elegant.html">Flexslider Elegant</a></li>
      <li><a href="elastic.html">Elastic</a></li>
      <li><a href="flash.html">Flash</a></li>
      <li><a href="rotating.html">Rotating</a></li>
      <li><a href="thumbnails.html">Thumbnails</a></li>
      <li><a href="usquare.html">Usquare</a></li>
      <li><a href="polaroid.html">Polaroid</a></li>
    </ul>
  </li>
  <li>
    <a href="#">FEATURES</a>
    <ul class="sub-menu">
      <li><a href="services-module.html">Services Module</a></li>
      <li><a href="blog-modules.html">Blog modules</a></li>
      <li><a href="portfolio-and-video-modules.html">Portfolio and video modules</a></li>
      <li><a href="libra-features.html">Libra features</a></li>
    </ul>
  </li>
  <li>
    <a href="#">PORTFOLIO</a>
    <ul class="sub-menu">
      <li><a href="portfolio-libra.html">Libra</a></li>
      <li><a href="portfolio-pinterest.html">Pinterest</a></li>
      <li><a href="portfolio-slide-detail.html">Slide Detail</a></li>
      <li><a href="portfolio-filterable.html">Filterable</a></li>
      <li><a href="portfolio-2-columns.html">2 Columns</a></li>
      <li><a href="portfolio-3-columns.html">3 Columns</a></li>
      <li><a href="portfolio-4-columns.html">4 Columns</a></li>
      <li><a href="portfolio-big-image.html">Big Image</a></li>
      <li><a href="portfolio-slider.html">Slider</a></li>
      <li><a href="portfolio-project-detail-1.html">Project Detail #1</a></li>
      <li><a href="portfolio-project-detail-2.html">Project detail #2</a></li>
    </ul>
  </li>
  <li>
    <a href="#">PAGES</a>
    <ul class="sub-menu">
      <li>
        <a href="testimonials.html">Testimonials</a></li>
      <li>
        <a href="#">Blog</a>
        <ul class="sub-menu">
          <li><a href="blog-libra-big.html">Libra Big</a></li>
          <li><a href="blog-libra-small.html">Libra Small</a></li>
          <li><a href="blog-elegant.html">Elegant</a></li>
          <li><a href="blog-big-thumbnails.html">Big Thumbnails</a></li>
          <li><a href="blog-small-thumbnails.html">Small Thumbnails</a></li>
          <li><a href="blog-pinterest.html">Pinterest</a></li>
        </ul>
      </li>
      <li>
        <a href="pages-faq.html">FAQ</a>
      </li>
      <li>
        <a href="#">About</a>
        <ul class="sub-menu">
          <li><a href="accordion-style.html">Accordion Style</a></li>
          <li><a href="circle-style.html">Circle Style</a></li>
          <li><a href="u-square-style.html">U-square style</a></li>
        </ul>
      </li>
      <li>
        <a href="error-404.html">Error 404</a>
      </li>
    </ul>
  </li>
  <li>
    <a href="#">SHORTCODES</a>
    <ul class="sub-menu">
      <li><a href="shortcodes-alert-box-buttons.html">Alert box &amp; Buttons</a></li>
      <li><a href="shortcodes-charts.html">Charts</a></li>
      <li><a href="shortcodes-icon-section.html">Icon section</a></li>
      <li><a href="shortcodes-media-widgets.html">Media &amp; Widgets</a></li>
      <li><a href="shortcodes-mix-various.html">Mix &amp; Various</a></li>
      <li><a href="shortcodes-table-box-prices.html">Table &amp; Box prices</a></li>
      <li><a href="shortcodes-typography.html">Typography</a></li>
    </ul>
  </li>
  <li>
    <a href="#">CONTACT</a>
    <ul class="sub-menu">
      <li><a href="get-in-touch.html">With MAP</a></li>
      <li><a href="get-in-touch-2.html">Without MAP</a></li>
    </ul>
  </li>
</ul>

app/views/layouts/template_parts/_nav_bar.html.erb
<nav class="navbar navbar-inverse" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><%= image_tag 'images/logo.png', alt: 'logo' %></a>
    </div>

    <div class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <li class="<%= active_menu_item('login') %>"><%= render('layouts/template_parts/link_to_login_logout') %></li>

        <% if user_signed_in? %>
          <li class="<%= active_menu_item('user') %>"><a href=<%= user_profile_path %>><%= I18n.t('main_menu.profile') %></a></li>
        <% end %>

        <li class="<%= active_menu_item('home') %>"><a href="about-us.html">About Us</a></li>
        <li><a href="services.html">Services</a></li>
        <li><a href="portfolio.html">Portfolio</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu">
            <li><a href="blog-item.html">Blog Single</a></li>
            <li><a href="pricing.html">Pricing</a></li>
            <li><a href="404.html">404</a></li>
          </ul>
        </li>
        <li><a href="blog.html">Blog</a></li>
        <li><a href="contact-us.html">Contact</a></li>
      </ul>
    </div>
  </div>
  <!--/.container-->
</nav>

app/views/layouts/template_parts/_partners.html.erb
<section id="partner">
  <div class="container">
    <div class="center fadeInDown">
      <h2>Our Partners</h2>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
    </div>

    <div class="partners">
      <ul>
        <li>
          <a href="#"><%= image_tag 'images/partners/brand-1.png', class: "img-responsive fadeInDown", 'data-wow-duration': "1000ms", 'data-wow-delay': "300ms" %></a>
        </li>
        <li>
          <a href="#"><%= image_tag 'images/partners/brand-2.png', class: "img-responsive fadeInDown", 'data-wow-duration': "1000ms", 'data-wow-delay': "600ms" %></a>
        </li>
        <li>
          <a href="#"><%= image_tag 'images/partners/brand-3.png', class: "img-responsive fadeInDown", 'data-wow-duration': "1000ms", 'data-wow-delay': "900ms" %></a>
        </li>
        <li>
          <a href="#"><%= image_tag 'images/partners/brand-4.png', class: "img-responsive fadeInDown", 'data-wow-duration': "1000ms", 'data-wow-delay': "1200ms" %></a>
        </li>
        <li>
          <a href="#"><%= image_tag 'images/partners/brand-5.png', class: "img-responsive fadeInDown", 'data-wow-duration': "1000ms", 'data-wow-delay': "1500ms" %></a>
        </li>
      </ul>
    </div>
  </div>
  <!--/.container-->
</section>

app/views/layouts/template_parts/_recent_works.html.erb
<section id="recent-works">
  <div class="container">
    <div class="center fadeInDown">
      <h2>Recent Works</h2>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
    </div>

    <div class="row">
      <%= render('layouts/template_parts/pretty_photo', locals: { image_url: 'images/portfolio/item-1.png'}) %>
      <%= render('layouts/template_parts/pretty_photo', locals: { image_url: 'images/portfolio/item-2.png'}) %>
      <%= render('layouts/template_parts/pretty_photo', locals: { image_url: 'images/portfolio/item-3.png'}) %>
      <%= render('layouts/template_parts/pretty_photo', locals: { image_url: 'images/portfolio/item-4.png'}) %>
      <%= render('layouts/template_parts/pretty_photo', locals: { image_url: 'images/portfolio/item-5.png'}) %>
      <%= render('layouts/template_parts/pretty_photo', locals: { image_url: 'images/portfolio/item-6.png'}) %>
    </div>
    <!--/.row-->
    <div class="clearfix text-center">
      <br>
      <br>
      <%= link_to 'Show More', '#', class: 'btn btn-primary' %>
    </div>
  </div>
  <!--/.container-->
</section>

app/views/layouts/template_parts/_services.html.erb
<section id="services" class="service-item">
  <div class="container">
    <div class="center fadeInDown">
      <h2>Our Service</h2>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
    </div>

    <div class="row">
      <%= render('layouts/template_parts/service', locals: { image_url: 'images/services/ux.svg', title: 'UI/UX Design', text: 'Hydroderm is the highly desired anti-aging cream on'}) %>
      <%= render('layouts/template_parts/service', locals: { image_url: 'images/services/web.svg', title: 'Web Design', text: 'Hydroderm is the highly desired anti-aging cream on'}) %>
      <%= render('layouts/template_parts/service', locals: { image_url: 'images/services/motion.svg', title: 'Motion Graphics', text: 'Hydroderm is the highly desired anti-aging cream on'}) %>
      <%= render('layouts/template_parts/service', locals: { image_url: 'images/services/mobile-ui.svg', title: 'Mobile UI/UX', text: 'Hydroderm is the highly desired anti-aging cream on'}) %>
      <%= render('layouts/template_parts/service', locals: { image_url: 'images/services/web-app.svg', title: 'Web Applications', text: 'Hydroderm is the highly desired anti-aging cream on'}) %>
      <%= render('layouts/template_parts/service', locals: { image_url: 'images/services/mobile-ui.svg', title: 'SEO Marketing', text: 'Hydroderm is the highly desired anti-aging cream on'}) %>
    </div>
    <!--/.row-->
  </div>
  <!--/.container-->
</section>

app/views/layouts/template_parts/_skills.html.erb
<section id="middle" class="skill-area" style="background-image: url(<%= asset_url('images/skill-bg.png')%>)">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 fadeInDown">
        <div class="skill">
          <h2>Our Skills</h2>
          <p>All users on MySpace will know that there are millions of people out there. Every <br> day besides so many people joining this community.</p>
        </div>
      </div>
      <!--/.col-sm-6-->

      <div class="col-sm-6">
        <div class="progress-wrap">
          <h3>Graphic Design</h3>
          <div class="progress">
            <div class="progress-bar  color1" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 85%">
              <span class="bar-width">85%</span>
            </div>

          </div>
        </div>

        <div class="progress-wrap">
          <h3>HTML</h3>
          <div class="progress">
            <div class="progress-bar color2" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 95%">
              <span class="bar-width">95%</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="progress-wrap">
          <h3>CSS</h3>
          <div class="progress">
            <div class="progress-bar color3" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
              <span class="bar-width">80%</span>
            </div>
          </div>
        </div>

        <div class="progress-wrap">
          <h3>Wordpress</h3>
          <div class="progress">
            <div class="progress-bar color4" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
              <span class="bar-width">90%</span>
            </div>
          </div>
        </div>
      </div>

    </div>
    <!--/.row-->
  </div>
  <!--/.container-->
</section>

app/views/layouts/template_parts/_small_title.html.haml
.page-title{ style: "background-image: url(#{asset_path('images/page-title.png')})" }
  %h1
    = locals[:title]

app/views/layouts/template_parts/_socials.html.erb
<div class="widget-last widget widget_text">
  <div class="textwidget">
    <div class="socials-default-small facebook-small default">
      <a href="# " class="socials-default-small default facebook" >facebook</a>
    </div>

    <div class="socials-default-small skype-small default">
      <a href="# " class="socials-default-small default skype" >skype</a>
    </div>

    <div class="socials-default-small linkedin-small default">
      <a href="#" class="socials-default-small default linkedin" >linkedin</a>
    </div>

    <div class="socials-default-small twitter-small default">
      <a href="#" class="socials-default-small default twitter" >twitter</a>
    </div>

    <div class="socials-default-small flickr-small default">
      <a href="#" class="socials-default-small default flickr" >flickr</a>
    </div>

    <div class="socials-default-small rss-small default">
      <a href="#" class="socials-default-small default rss" >rss</a>
    </div>

    <div class="socials-default-small pinterest-small default">
      <a href="#" class="socials-default-small default pinterest" >pinterest</a>

    </div>
  </div>
</div>

app/views/layouts/template_parts/_testiomanial.html.erb
<div class="single-slide">
  <div class="slide-img">
    <%= image_tag locals[:image_url], alt: '' %>
  </div>
  <div class="content">
    <%= image_tag 'images/review.png', alt: '' %>
    <p><%= locals[:testiomanial] %></p>
    <h4>- <%= locals[:name] %></h4>
  </div>
</div>

app/views/layouts/template_parts/_user_name_login.html.haml
- if user_signed_in?
  = link_to current_user.email, user_profile_path
- else
  = link_to I18n.t('main_menu.login'), new_user_session_path