config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/auth/do_omniauth', to: 'omniauth_callbacks#do_omniauth', as: :auth_callback_do
    get '/users/auth/service_sign_up', to: 'omniauth_callbacks#service_sign_up_users', as: :service_sign_up_users
    post '/users/auth/create_user_and_service', to: 'omniauth_callbacks#create_user_and_service', as: :create_user_and_service
  end

#  authenticated(:user) do

    resource :user_profile, only: [:show, :update], controller: 'user_profile/users', as: :user_profile
    scope module: :user_profile do
      resources :services, only: [:destroy], as: :user_profile_services
    end

    resource :user_cabinet, only: [:show, :update], controller: 'user_cabinet/users', as: :user_cabinet
    namespace :user_cabinet do
      resources :galleries
      resource :category, only: :update
      resources :articles
    end


    # patch 'users/:id/update_category', to: 'user_cabinet/users#update_category', as: :user_update_category
    #
    # resources :users, only: [:show, :edit, :update] do
    #   get :profile, on: :member, to: 'user_profile/users#show', as: :user_profile
    #   put :profile, on: :member, to: 'user_profile/users#update'
    #
    #   scope module: 'user_profile' do
    #     resources :services, only: [:destroy]
    #   end
    #
    #   get :cabinet, on: :member, to: 'user_cabinet/users#show', as: :user_cabinet
    #   scope module: 'user_cabinet' do
    #     resources :galleries
    #     resources :pictures
    #   end
    #
    #   resources :articles
    # end
    #
    # resources :grades
    # resources :articles, only: [:index, :show]
#    root to: "secret#index", as: :authenticated_root
#  end

  resources :grades, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :galleries, only: [:index, :show]
  root to: 'home#index'

  def authenticated_root
    user_profile
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UserConcern
  include TaggableConcern
  include GradeConcern
  include CategoryConcern

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, omniauth_providers: [:github, :facebook, :vkontakte]

  has_many :services, dependent: :destroy
  has_many :galleries, dependent: :destroy
  has_many :pictures, through: :galleries
  has_many :articles, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_one :user_parameter, dependent: :destroy


  has_one_attached :avatar
  has_one_attached :main_image

  validates :avatar, content_type: IMAGE_CONTENT_TYPES
  validates :main_image, content_type: IMAGE_CONTENT_TYPES
end

app/controllers/user_cabinet/articles_controller.rb
# encoding: utf-8
module UserCabinet
  class ArticlesController < PrivateAreaController

    def new
      super do
        @resource = Article.new(user_id: current_user.id)
      end
    end

    def create
      super do
        @resource = Article.create(article_params.merge!(user_id: current_user.id,
                                                         state: :draft,
                                                         article_type: :service))
        unless @resource.persisted?
          render :new
          return
        end
        redirect_to user_cabinet_article_path(id: @resource.id)
      end
    end

    def update
      super do
        @resource.update(article_params)
        if @resource.errors.count == 0
          render json: attributes_mask_to_json(@resource, article_params),  status: :ok
        else
          render json: @resource.errors.full_messages.join(', '), status: :unprocessable_entity
        end
      end
    end

    def destroy
      super do
        ActiveRecord::Base.transaction do
          @resource.destroy!
        end
        redirect_to user_cabinet_path
      end
    end

    private

    def article_params
      params.required(:article).permit(:name, :main_description, :short_description, :state, :article_type,
                                       :min_quantity, :max_quantity, :min_age, :max_age, :seo_description,
                                       :seo_keywords, :duration_minutes, :main_image)
    end

    def menu_action_items
      ['user']
    end
  end
end

app/controllers/user_cabinet/categories_controller.rb
# encoding: utf-8

module UserCabinet
  class CategoriesController < PrivateUserController

    def update
      super do
        presenter = UserCategoryPresenter.new.from_json_string(user_categories_params[:categories])
        ActiveRecord::Base.transaction do
          @resource.clear_categories
          presenter.categories.each do |category|
            @resource.add_category(category[:name])
          end
        end

        render json: presenter.to_json,  status: :ok
      end
    end

    def user_categories_params
      params.required(:user).permit(:categories)
    end

  end
end

app/controllers/user_cabinet/galleries_controller.rb
# encoding: utf-8
module UserCabinet
  class GalleriesController < PrivateAreaController

    def new
      super do
        @resource = Gallery.new
      end
    end

    def create
      super do
        presenter = UserGalleryPresenter.new
        @resource = presenter.create(view_context)
        if @resource.persisted?
          redirect_to user_cabinet_gallery_path(id: @resource.id)
          return
        end
        render :new
      end
    end


    def update
      super do
        presenter = UserGalleryPresenter.new(gallery_params)
        @resource = presenter.update(@resource, view_context)
        if @resource.errors.count == 0
          render json: attributes_mask_to_json(@resource, gallery_params),  status: :ok
        else
          render json: presenter.errors_to_json, status: :unprocessable_entity
        end
      end
    end


    private

    def gallery_params
      params.required(:gallery).permit(:name, :description, :user_id, :image_for_cover)
    end

    def menu_action_items
      ['user']
    end
  end
end

app/controllers/user_cabinet/pictures_controller.rb
# encoding: utf-8
module UserCabinet
  class PicturesController < PrivateAreaController

    def create
      super do
        ActiveRecord::Base.transaction do
          @resource = Picture.create(picture_params.merge!(gallery_id: params.require(:gallery_id),
                                                           state: :active))
        end
        if @resource.persisted?
          render json: attributes_mask_to_json(@resource, picture_params),  status: :created,
                 location: user_cabinet_gallery_picture_path(gallery_id: params[:gallery_id], id: @resource.id)
        else
          render json: @resource.errors.full_messages.join(', '), status: :unprocessable_entity
        end
      end
    end


    def update
      # super do
      #   presenter = UserGalleryPresenter.new(gallery_params)
      #   @resource = presenter.update(@resource, view_context)
      #   if @resource.errors.count == 0
      #     render json: attributes_mask_to_json(@resource, gallery_params),  status: :ok
      #   else
      #     render json: presenter.errors_to_json, status: :unprocessable_entity
      #   end
      # end
    end


    private

    def picture_params
      params.required(:picture).permit(:name, :description, :image, :state)
    end

    def menu_action_items
      ['user']
    end
  end
end

app/controllers/user_cabinet/users_controller.rb
# encoding: utf-8
module UserCabinet
  class UsersController < PrivateUserController

    def update
      super do
        presenter = UserCabinetPresenter.new(user_cabinet_params)
        presenter.update(@resource)
        if presenter.errors.count == 0
          render json: attributes_mask_to_json(@resource, user_cabinet_params),  status: :ok
        else
          render json: presenter.errors_to_json, status: :unprocessable_entity
        end
      end
    end

    def menu_action_items
      ['user']
    end

    def user_cabinet_params
      params.required(:user).permit(:main_image, :main_description)
    end
  end
end

app/controllers/user_profile/users_controller.rb
# encoding: utf-8

module UserProfile
  class UsersController < PrivateUserController

    def show
      super do
        @resource = UserProfilePresenter.new(@resource, view_context)
      end
    end

    def update
      super do
        @resource.update(user_profile_params)
        if @resource.errors.count == 0
          presenter = UserProfilePresenter.new(@resource, view_context)
          render json: Hash[*user_profile_params.keys.map{|key| [key, presenter.send(key)]}.flatten],  status: :ok
        else
          render json: @resource.errors.full_messages.joins(', '), status: :unprocessable_entity
        end
      end
    end

    def menu_action_items
      ['user']
    end

    def user_profile_params
      params.required(:user_profile_presenter).permit(:avatar, :nick_name)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_update_path_for(resource)
    user_path(resource)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  def show
    super do
      @mode = params[:mode].present? ? params[:mode] : 'profile'
      @services = @resource.services
    end
  end

  def update
    super do
      ActiveRecord::Base.transaction do
        # Категории
        if params[:category].present?
          @resource.clear_categories
          if params[:user].present? && params[:user][:categories].present?
            params[:user][:categories].keys.each do |category_name|
              @resource.add_category(category_name)
             end
          end
        end
      end
      redirect_to user_path(id: @resource.id, mode: 'cabinet')
    end
  end


  def menu_action_items
    ['user']
  end

  def user_params
    params.required(:user).permit(:main_image, :categories)
  end
end

app/views/user_cabinet/users/_about_me.html.haml
.blog-item
  .blog-content
    = rc_text_field(@resource, :main_description, user_cabinet_path)

app/views/user_cabinet/users/_articles.html.haml
%ul.portfolio-filter.text-center
  %li
    %a.btn.btn-default.active{"data-filter" => "*", :href => "#"} All Works
  %li
    %a.btn.btn-default{"data-filter" => ".bootstrap", :href => "#"} Creative
  %li
    %a.btn.btn-default{"data-filter" => ".html", :href => "#"} Photography
  %li
    %a.btn.btn-default{"data-filter" => ".wordpress", :href => "#"} Web Development
    / /#portfolio-filter
  .row
    .portfolio-items
      .portfolio-item.apps.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-1.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-1.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.joomla.bootstrap.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-2.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-2.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.bootstrap.wordpress.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-3.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-3.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.joomla.wordpress.apps.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-4.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-4.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.joomla.html.bootstrap.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-5.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-5.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.wordpress.html.apps.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-1.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-1.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.joomla.html.bootstrap.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-6.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-6.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item
      .portfolio-item.wordpress.html.apps.col-xs-12.col-sm-4.col-md-3.single-work
        .recent-work-wrap
          =image_tag('images/portfolio/item-2.png', class: 'img-responsive', alt: '')
          .overlay
            .recent-work-inner
              = link_to(asset_url('images/portfolio/item-2.png'), class: 'preview', rel: 'prettyPhoto') do
                %i.fa.fa-plus
        / /.portfolio-item

app/views/user_cabinet/users/_category_list.html.haml
.widget.category
  = rc_list_field(@resource, :categories, user_cabinet_category_path)

app/views/user_cabinet/users/_change_image.html.haml
.widget.search
  =form_for(@resource, as: User, url: user_cabinet_path, method: :put, role: "form") do |f|
    = f.file_field :main_image

app/views/user_cabinet/users/_left_part_cabinet.html.erb
  <%= render('main_image') %>
  <%= render('about_me') %>
  <%= render('articles') %>

app/views/user_cabinet/users/_main_image.html.haml
.blog-item
  = rc_edit_image_field(@resource, :main_image, user_cabinet_path, @resource.decorate.main_image_cover)
  -#= link_to asset_path('images/blog1.png') do
  -#  = rc_edit_image_field(@resource, :main_image, user_cabinet_path, @resource.decorate.main_image_cover)
  -#  = image_tag('images/blog1.png', class: 'img-responsive img-blog', width: "100%", alt: "")
  -#.blog-content
  -#  = render('change_image')

app/views/user_cabinet/users/_programs.html.haml
.blog-item
  .blog-content
    = link_to I18n.t('user.show.my_programs').upcase, '#', class: 'blog_cat'
    %h2
      %a{:href => "blog-item.html"} Программы, которые я делаю
    %h3 Curabitur quis libero leo, pharetra mattis eros. Praesent consequat libero eget dolor convallis vel rhoncus magna scelerisque. Donec nisl ante, elementum eget posuere a, consectetur a metus. Proin a adipiscing sapien. Suspendisse vehicula porta lectus vel semper. Nullam sapien elit, lacinia eu tristique non.posuere at mi. Morbi at turpis id urna ullamcorper ullamcorper.
    %a.readmore{:href => "blog-item.html"}
      = I18n.t('read_more')
      %i.fa.fa-long-arrow-right
    .articles-list
      = render('articles')

app/views/user_cabinet/users/_right_part_cabinet.html.erb
  <%= render('category_list') %>
  <%= render('user_cabinet/galleries/gallery_column', locals: { galleries: @resource.galleries }) %>

  <div class="widget search">
    <form role="form">
      <input type="text" class="form-control search_box" autocomplete="off" placeholder="Search Here">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
  <!--/.search-->


  <div class="widget archieve">
    <h3>Categories</h3>
    <div class="row">
      <div class="col-sm-12">
        <ul class="blog_archieve">
          <li><a href="#">December 2013 <span class="pull-right">(97)</span></a></li>
          <li><a href="#">November 2013 <span class="pull-right">(32)</span></a></li>
          <li><a href="#">October 2013 <span class="pull-right">(19)</span></a></li>
          <li><a href="#">September 2013 <span class="pull-right">(08)</span></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!--/.archieve-->

  <div class="widget popular_post">
    <h3>Popular Post</h3>
    <ul>
      <li>
        <a href="#">
          <img src="images/post1.png" alt="">
          <p>Can you get free games for you</p>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="images/post2.png" alt="">
          <p>Can you get free games for you</p>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="images/post3.png" alt="">
          <p>Can you get free games for you</p>
        </a>
      </li>
    </ul>
  </div>
  <!--/.archieve-->


  <!--/.blog_gallery-->

  <div class="widget social_icon">
    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-twitter"></a>
    <a href="#" class="fa fa-linkedin"></a>
    <a href="#" class="fa fa-pinterest"></a>
    <a href="#" class="fa fa-github"></a>
  </div>

app/views/user_cabinet/users/show.html.haml
= render('layouts/template_parts/small_title', locals: { title: I18n.t('user.show.title_cabinet') })
%section#cabinet-page
  .container.blog
    .row
      .col-md-8
        = render('left_part_cabinet')
      %aside.col-md-4
        = render('right_part_cabinet')