config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/auth/do_omniauth', to: 'omniauth_callbacks#do_omniauth', as: :auth_callback_do
    get '/users/auth/service_sign_up', to: 'omniauth_callbacks#service_sign_up_users', as: :service_sign_up_users
    post '/users/auth/create_user_and_service', to: 'omniauth_callbacks#create_user_and_service', as: :create_user_and_service
  end

#  authenticated(:user) do

    resource :user_profile, only: [:show, :update], controller: 'user_profile/users', as: :user_profile
    scope module: :user_profile do
      resources :services, only: [:destroy], as: :user_profile_services
    end

    resource :user_cabinet, only: [:show, :update], controller: 'user_cabinet/users', as: :user_cabinet
    namespace :user_cabinet do
      resources :galleries
      resource :category, only: :update
      resources :articles
    end


    # patch 'users/:id/update_category', to: 'user_cabinet/users#update_category', as: :user_update_category
    #
    # resources :users, only: [:show, :edit, :update] do
    #   get :profile, on: :member, to: 'user_profile/users#show', as: :user_profile
    #   put :profile, on: :member, to: 'user_profile/users#update'
    #
    #   scope module: 'user_profile' do
    #     resources :services, only: [:destroy]
    #   end
    #
    #   get :cabinet, on: :member, to: 'user_cabinet/users#show', as: :user_cabinet
    #   scope module: 'user_cabinet' do
    #     resources :galleries
    #     resources :pictures
    #   end
    #
    #   resources :articles
    # end
    #
    # resources :grades
    # resources :articles, only: [:index, :show]
#    root to: "secret#index", as: :authenticated_root
#  end

  resources :grades, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :galleries, only: [:index, :show]
  root to: 'home#index'

  def authenticated_root
    user_profile
  end
end

app/views/shared/_alert_notice.html.haml
.status.alert.alert-success{ style: "display: #{ notice.nil? ? 'none' : 'block' }"}
  = notice
.status.alert.alert-danger{ style: "display: #{ alert.nil? ? 'none' : 'block' }" }
  = alert

app/views/shared/_gallery_column.html.haml
.widget.blog_gallery
  %h3
    = I18n.t('user.show.galleries')
  %ul.sidebar-gallery.clearfix
    - locals[:galleries].each do |gallery|
      %li
        = link_to user_gallery_path(user_id: gallery.user_id, id: gallery.id) do
          = cover_gallery_small(gallery)
  = link_to 'blog-item.html', class: :readmore do
    Read More
    %i{ class: 'fa fa-long-arrow-right' }

app/views/shared/_resource_alert_notice.html.haml
.status.alert.alert-success{ style: "display: #{ notice.nil? ? 'none' : 'block' }"}
  = notice
- if alert || (@resource && @resource.errors.any?)
  .status.alert.alert-danger{ style: 'display: block' }
    = alert if alert
    - if @resource && @resource.errors.any?
      <br/>
      = I18n.t("errors.messages.not_saved", count: @resource.errors.count, resource: @resource.class.model_name.human.downcase)
      = simple_format(errors_to_str(@resource))

app/views/shared/_show_attributes.html.haml
%div
  %table
    %tr
      %th
        Attributes
      %th
        Values
    - @resource.attributes.each do |attribute|
      %tr
        %td
          = @resource.class.name.constantize.human_attribute_name(attribute[0])
        %td
          = attribute[1]

app/views/shared/_show_index.html.haml
%div
  %table
    %tr
      - locals[:object_class].columns.map(&:name).each do |attribute|
        %th
          = attribute
    - @collection.each do |record|
      %tr
        - locals[:object_class].columns.map(&:name).each do |attribute|
          %td
            = record.send(attribute)

app/views/shared/_show_tags_panel.html.haml
%ul.portfolio-filter.text-center
  %li
    %a.btn.btn-default.active{"data-filter" => "*", :href => "#"} All Works
  %li
    %a.btn.btn-default{"data-filter" => ".bootstrap", :href => "#"} Creative
  %li
    %a.btn.btn-default{"data-filter" => ".html", :href => "#"} Photography
  %li
    %a.btn.btn-default{"data-filter" => ".wordpress", :href => "#"} Web Development

app/views/shared/_terms_of_service_short.html.haml
.container
  .center.fadeInDown
    %h2
      = I18n.t('forms.login.terms_of_service')
    %p.lead
      = simple_format(I18n.t('forms.login.service_preview'))
  .blog
    .row.col-md-8
      .blog-item
        .blog-content
          %h3
            = simple_format(I18n.t('terms_of_service_main_short'))
          = link_to 'blog-item.html', class: 'readmore' do
            = I18n.t('read_more')
            %i.fa.fa-long-arrow-right